version: '3.8'
services:
  chroma:
    image: chromadb/chroma:1.0.12
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    ports:
      - "${CHROMADB_PORT}:8000"
    volumes:
      - ./data/chromadb:/chroma/chroma
  
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
