version: '3.8'
services:
  grpc-server:
    build: .
    container_name: grpc-server
    ports:
      - "${GRPC_PORT}:50051"
    environment:
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50051
      - REDIS_HOST=redis
      - CHROMADB_HOST=chroma
    depends_on:
      - redis
      - chroma
  chroma:
    image: chromadb/chroma:1.0.12
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    ports:
      - "${CHROMADB_PORT}:8000"
    volumes:
      - ./data/chromadb:/chroma/chroma
  
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
