# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/chats/chat_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'services/chats/chat_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!services/chats/chat_service.proto\x12\x0eservices.chats\"\xa0\x01\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x04 \x01(\t\x12\x16\n\x0erecent_history\x18\x05 \x01(\t\x12\x31\n\x0ctts_settings\x18\x06 \x01(\x0b\x32\x1b.services.chats.TTSSettings\"\xa5\x01\n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12*\n\x08metadata\x18\x05 \x01(\x0b\x32\x18.services.chats.Metadata\x12\x15\n\raudio_content\x18\x06 \x01(\x0c\x12\r\n\x05\x65rror\x18\x07 \x01(\t\"j\n\x0bTTSSettings\x12\x12\n\nenable_tts\x18\x01 \x01(\x08\x12\x10\n\x08voice_id\x18\x02 \x01(\t\x12\x35\n\x0evoice_settings\x18\x03 \x01(\x0b\x32\x1d.services.chats.VoiceSettings\"u\n\rVoiceSettings\x12\x11\n\tstability\x18\x01 \x01(\x02\x12\x18\n\x10similarity_boost\x18\x02 \x01(\x02\x12\r\n\x05style\x18\x03 \x01(\x02\x12\x19\n\x11use_speaker_boost\x18\x04 \x01(\x08\x12\r\n\x05speed\x18\x05 \x01(\x02\"\x1d\n\x08Metadata\x12\x11\n\ttimestamp\x18\x01 \x01(\t2\xab\x01\n\x0b\x43hatService\x12M\n\x0eProcessMessage\x12\x1b.services.chats.ChatRequest\x1a\x1c.services.chats.ChatResponse\"\x00\x12M\n\nStreamChat\x12\x1b.services.chats.ChatRequest\x1a\x1c.services.chats.ChatResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.chats.chat_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=54
  _globals['_CHATREQUEST']._serialized_end=214
  _globals['_CHATRESPONSE']._serialized_start=217
  _globals['_CHATRESPONSE']._serialized_end=382
  _globals['_TTSSETTINGS']._serialized_start=384
  _globals['_TTSSETTINGS']._serialized_end=490
  _globals['_VOICESETTINGS']._serialized_start=492
  _globals['_VOICESETTINGS']._serialized_end=609
  _globals['_METADATA']._serialized_start=611
  _globals['_METADATA']._serialized_end=640
  _globals['_CHATSERVICE']._serialized_start=643
  _globals['_CHATSERVICE']._serialized_end=814
# @@protoc_insertion_point(module_scope)
