# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/chats/chat_service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'services/chats/chat_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!services/chats/chat_service.proto\x12\x0eservices.chats\"\xe1\x01\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x39\n\x07\x63ontext\x18\x04 \x03(\x0b\x32(.services.chats.ChatRequest.ContextEntry\x12\x31\n\x0ctts_settings\x18\x05 \x01(\x0b\x32\x1b.services.chats.TTSSettings\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"j\n\x0bTTSSettings\x12\x12\n\nenable_tts\x18\x01 \x01(\x08\x12\x10\n\x08voice_id\x18\x02 \x01(\t\x12\x35\n\x0evoice_settings\x18\x03 \x01(\x0b\x32\x1d.services.chats.VoiceSettings\"u\n\rVoiceSettings\x12\x11\n\tstability\x18\x01 \x01(\x02\x12\x18\n\x10similarity_boost\x18\x02 \x01(\x02\x12\r\n\x05style\x18\x03 \x01(\x02\x12\x19\n\x11use_speaker_boost\x18\x04 \x01(\x08\x12\r\n\x05speed\x18\x05 \x01(\x02\"\x9d\x01\n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x31\n\x08metadata\x18\x05 \x01(\x0b\x32\x1f.services.chats.MetadataMessage\x12\x15\n\raudio_content\x18\x06 \x01(\x0c\"\xba\x01\n\x0fMetadataMessage\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x12\n\nturn_count\x18\x02 \x01(\x05\x12L\n\x0f\x61\x64\x64itional_data\x18\x03 \x03(\x0b\x32\x33.services.chats.MetadataMessage.AdditionalDataEntry\x1a\x35\n\x13\x41\x64\x64itionalDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xab\x01\n\x0b\x43hatService\x12M\n\x0eProcessMessage\x12\x1b.services.chats.ChatRequest\x1a\x1c.services.chats.ChatResponse\"\x00\x12M\n\nStreamChat\x12\x1b.services.chats.ChatRequest\x1a\x1c.services.chats.ChatResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.chats.chat_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_CHATREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_METADATAMESSAGE_ADDITIONALDATAENTRY']._loaded_options = None
  _globals['_METADATAMESSAGE_ADDITIONALDATAENTRY']._serialized_options = b'8\001'
  _globals['_CHATREQUEST']._serialized_start=54
  _globals['_CHATREQUEST']._serialized_end=279
  _globals['_CHATREQUEST_CONTEXTENTRY']._serialized_start=233
  _globals['_CHATREQUEST_CONTEXTENTRY']._serialized_end=279
  _globals['_TTSSETTINGS']._serialized_start=281
  _globals['_TTSSETTINGS']._serialized_end=387
  _globals['_VOICESETTINGS']._serialized_start=389
  _globals['_VOICESETTINGS']._serialized_end=506
  _globals['_CHATRESPONSE']._serialized_start=509
  _globals['_CHATRESPONSE']._serialized_end=666
  _globals['_METADATAMESSAGE']._serialized_start=669
  _globals['_METADATAMESSAGE']._serialized_end=855
  _globals['_METADATAMESSAGE_ADDITIONALDATAENTRY']._serialized_start=802
  _globals['_METADATAMESSAGE_ADDITIONALDATAENTRY']._serialized_end=855
  _globals['_CHATSERVICE']._serialized_start=858
  _globals['_CHATSERVICE']._serialized_end=1029
# @@protoc_insertion_point(module_scope)
