# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/vector_store/vector_store_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'services/vector_store/vector_store_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0services/vector_store/vector_store_service.proto\x12\x15services.vector_store\"\xa7\x01\n\x18StoreConversationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x10\n\x08response\x18\x05 \x01(\t\x12\x31\n\x08metadata\x18\x06 \x01(\x0b\x32\x1f.services.vector_store.Metadata\";\n\x19StoreConversationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x1d\n\x08Metadata\x12\x11\n\ttimestamp\x18\x01 \x01(\t2\x8e\x01\n\x12VectorStoreService\x12x\n\x11StoreConversation\x12/.services.vector_store.StoreConversationRequest\x1a\x30.services.vector_store.StoreConversationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.vector_store.vector_store_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STORECONVERSATIONREQUEST']._serialized_start=76
  _globals['_STORECONVERSATIONREQUEST']._serialized_end=243
  _globals['_STORECONVERSATIONRESPONSE']._serialized_start=245
  _globals['_STORECONVERSATIONRESPONSE']._serialized_end=304
  _globals['_METADATA']._serialized_start=306
  _globals['_METADATA']._serialized_end=335
  _globals['_VECTORSTORESERVICE']._serialized_start=338
  _globals['_VECTORSTORESERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
