# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services.vector_store import vector_store_service_pb2 as services_dot_vector__store_dot_vector__store__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services/vector_store/vector_store_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorStoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreConversation = channel.unary_unary(
                '/services.vector_store.VectorStoreService/StoreConversation',
                request_serializer=services_dot_vector__store_dot_vector__store__service__pb2.StoreConversationRequest.SerializeToString,
                response_deserializer=services_dot_vector__store_dot_vector__store__service__pb2.StoreConversationResponse.FromString,
                _registered_method=True)


class VectorStoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreConversation,
                    request_deserializer=services_dot_vector__store_dot_vector__store__service__pb2.StoreConversationRequest.FromString,
                    response_serializer=services_dot_vector__store_dot_vector__store__service__pb2.StoreConversationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.vector_store.VectorStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.vector_store.VectorStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorStoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.vector_store.VectorStoreService/StoreConversation',
            services_dot_vector__store_dot_vector__store__service__pb2.StoreConversationRequest.SerializeToString,
            services_dot_vector__store_dot_vector__store__service__pb2.StoreConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
